# Generated by Django 5.2.1 on 2025-05-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='s3_audio_file_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='S3 Audio File URL'),
        ),
        migrations.AddField(
            model_name='novel',
            name='s3_audio_metadata_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='S3 Audio Metadata URL'),
        ),
    ]
