# Generated by Django 5.2.1 on 2025-05-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0002_novel_s3_audio_file_url_novel_s3_audio_metadata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkannotation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], db_index=True, default='completed', max_length=50),
        ),
    ]
