# Generated by Django 5.2.1 on 2025-06-08 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0003_alter_chunkannotation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('voice_actor_name', models.CharField(help_text='Name of the voice actor', max_length=100, unique=True)),
                ('s3_audio_data_url', models.URLField(help_text='URL to the voice actor audio data in S3')),
                ('s3_voice_actor_metadata_url', models.URLField(help_text='URL to the voice actor metadata in S3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voice',
                'verbose_name_plural': 'Voices',
            },
        ),
        migrations.AddField(
            model_name='sentenceannotation',
            name='voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentence_annotations', to='audiobook.voice', verbose_name='Voice Actor'),
        ),
    ]
