# Generated by Django 5.2.1 on 2025-06-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0004_voice_sentenceannotation_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='voice_actor_info',
            field=models.TextField(blank=True, help_text='Thông tin về diễn viên lồng tiếng', null=True),
        ),
        migrations.AlterField(
            model_name='voice',
            name='s3_audio_data_url',
            field=models.URLField(blank=True, help_text='URL to the voice actor audio data in S3', null=True),
        ),
        migrations.AlterField(
            model_name='voice',
            name='s3_voice_actor_metadata_url',
            field=models.URLField(blank=True, help_text='URL to the voice actor metadata in S3', null=True),
        ),
    ]
